### ISSUE TITLE
PDB-BRE_1.0.0.tar.gz  is corrupted?

### ISSUE THREAD

**Issue by rytakahashi** [ShutaoChen97/PDB-BRE#1]
tar zxvf PDB-BRE_1.0.0.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by ShutaoChen97** [comment]
Sorry, for some reason the previous package was not working .... 
We have re-uploaded the packages for PDB-BRE. Now you can download it via the following links: **https://github.com/ShutaoChen97/PDB-BRE/releases/download/v1.0.0/PDB-BRE_1.0.0.tar.gz** 
&
 **http://bliulab.net/PDB-BRE/downloads/PDB-BRE_1.0.0.tar.gz**.

If you have any further questions, please feel free to contact us.

**Comment by rytakahashi** [comment]
Many Thanks, now, yes!
